import sqlite3
import os


conn = sqlite3.connect("instance/easyGrade.db")
print("Opened database successfully")

conn.execute(
    """CREATE TABLE IF NOT EXISTS MAESTROS
        (MAESTRO_ID INTEGER PRIMARY KEY NOT NULL,
        NOMBRE VARCHAR NOT NULL,
        APELLIDO VARCHAR NOT NULL,
        CONTACTO_ID INTEGER,
        PASSWORD_ID VARCHAR NOT NULL,
        FOREIGN KEY (CONTACTO_ID) REFERENCES CONTACTOS(ID),
        FOREIGN KEY (PASSWORD_ID) REFERENCES PASSWORDS(ID))"""
)
print("Table MAESTROS created successfully")

conn.execute(
    """CREATE TABLE IF NOT EXISTS CONTACTO
        (CONTACTO_ID INTEGER PRIMARY KEY NOT NULL,
        TELEFONO VARCHAR,
        DIRECCION VARCHAR,
        CORREO_ELECTRONICO VARCHAR NOT NULL);"""
)
print("Table CONTACTO created successfully")

conn.execute(
    """CREATE TABLE IF NOT EXISTS MATERIAS
        (MATERIA_ID INTEGER PRIMARY KEY NOT NULL,
        NOMBRE VARCHAR NOT NULL,
        NIVEL VARCHAR NOT NULL,
        MAESTRO_ID INTEGER,
        FOREIGN KEY (MAESTRO_ID) REFERENCES MAESTROS(MAESTRO_ID));"""
)
print("Table MATERIAS created successfully")

conn.execute(
    """CREATE TABLE IF NOT EXISTS ALUMNOS
         (ALUMNO_ID INTEGER PRIMARY KEY NOT NULL,
         NOMBRE VARCHAR NOT NULL,
         APELLIDO VARCHAR NOT NULL,
         FECHA_NACIMIENTO DATE,
         PASSWORD_ID VARCHAR NOT NULL,
         CONTACTO_ID VARCHAR NOT NULL,
         FOREIGN KEY (PASSWORD_ID) REFERENCES PASSWORDS(PASSWORD_ID),
         FOREIGN KEY (CONTACTO_ID) REFERENCES CONTACTOS(CONTACTO_ID));"""
)
print("Table ALUMNOS created successfully")

conn.execute(
    """CREATE TABLE IF NOT EXISTS EJERCICIOS
         (EJERCICIOS_ID INTEGER PRIMARY KEY NOT NULL,
         DESCRIPCION VARCHAR NOT NULL,
         QUESTION VARCHAR NOT NULL,
         ANSWER VARCHAR NOT NULL,
         MATERIA_ID INTEGER NOT NULL,
         CALIFICACION INTEGER NOT NULL,
         FOREIGN KEY (MATERIA_ID) REFERENCES MATERIAS(MATERIA_ID));"""
)
print("Table EJERCICIOS created successfully")

conn.execute(
    """CREATE TABLE IF NOT EXISTS PASSWORDS
         (PASSWORD_ID INTEGER PRIMARY KEY NOT NULL,
         PASSWORD VARCHAR NOT NULL);"""
)
print("Table PASSWORDS created successfully")

conn.execute(
    """CREATE TABLE IF NOT EXISTS TAREAS
         (TAREA_ID INTEGER PRIMARY KEY NOT NULL,
         DESCRIPCION TEXT NOT NULL,
         MATERIA_ID INTEGER NOT NULL,
         ALUMNO_ID INTEGER NOT NULL,
         MAESTRO_ID INTEGER NOT NULL,
         CALIFICACION INTEGER NOT NULL,
         FOREIGN KEY (MATERIA_ID) REFERENCES MATERIAS(MATERIA_ID),
         FOREIGN KEY (ALUMNO_ID) REFERENCES ALUMNOS(ALUMNO_ID),
         FOREIGN KEY (MAESTRO_ID) REFERENCES MAESTROS(MAESTRO_ID));"""
)
print("Table TAREAS created successfully")

conn.execute(
    """CREATE TABLE IF NOT EXISTS EXAMENES
         (EXAMENES_ID INTEGER PRIMARY KEY NOT NULL,
         DESCRIPCION TEXT NOT NULL,
         MATERIA_ID INTEGER NOT NULL,
         ALUMNO_ID INTEGER NOT NULL,
         MAESTRO_ID INTEGER NOT NULL,
         CALIFICACION INTEGER NOT NULL,
         FOREIGN KEY (MATERIA_ID) REFERENCES MATERIAS(MATERIA_ID),
         FOREIGN KEY (ALUMNO_ID) REFERENCES ALUMNOS(ALUMNO_ID),
         FOREIGN KEY (MAESTRO_ID) REFERENCES MAESTROS(MAESTRO_ID));"""
)
print("Table EXAMENES created successfully")

conn.execute(
    """CREATE TABLE IF NOT EXISTS REGISTRO_MATERIAS_MAESTROS (
    MAESTRO_ID INTEGER NOT NULL,
    MATERIA_ID INTEGER NOT NULL,
    PRIMARY KEY (MAESTRO_ID, MATERIA_ID),
    FOREIGN KEY (MAESTRO_ID) REFERENCES MAESTROS(MAESTRO_ID),
    FOREIGN KEY (MATERIA_ID) REFERENCES MATERIAS(MATERIA_ID))"""
)
print("Table REGISTRO_MATERIAS_MAESTROS created successfully")

conn.execute(
    """CREATE TABLE IF NOT EXISTS REGISTRO_MATERIAS_ALUMNOS (
    MAESTRO_ID INTEGER NOT NULL,
    MATERIA_ID INTEGER NOT NULL,
    PRIMARY KEY (MAESTRO_ID, MATERIA_ID),
    FOREIGN KEY (MAESTRO_ID) REFERENCES MAESTROS(MAESTRO_ID),
    FOREIGN KEY (MATERIA_ID) REFERENCES MATERIAS(MATERIA_ID)
    );"""
)
print("Table REGISTRO_MATERIAS_ALUMNOS created successfully")

conn.execute(
    """CREATE TABLE IF NOT EXISTS CALIFICACIONES_TAREAS (
    TAREA_ID INTEGER NOT NULL,
    ALUMNO_ID INTEGER NOT NULL,
    CALIFICACION INTEGER NOT NULL,
    PRIMARY KEY (TAREA_ID, ALUMNO_ID),
    FOREIGN KEY (TAREA_ID) REFERENCES TAREAS(TAREA_ID),
    FOREIGN KEY (ALUMNO_ID) REFERENCES ALUMNOS(ALUMNO_ID));"""
)
print("Table CALIFICACIONES_TAREAS created succesfully")

conn.execute(
    """CREATE TABLE IF NOT EXISTS CALIFICACIONES_EJERCICIOS (
    EJERCICIOS_ID INTEGER NOT NULL,
    ALUMNO_ID INTEGER NOT NULL,
    CALIFICACION INTEGER NOT NULL,
    FOREIGN KEY (EJERCICIOS_ID) REFERENCES EJERCICIOS(EJERCICIOS_ID),
    FOREIGN KEY (ALUMNO_ID) REFERENCES ALUMNOS(ALUMNO_ID));"""
)
print("Table CALIFICACIONES_EJERCICIOS created successfully")

conn.execute(
    """CREATE TABLE IF NOT EXISTS CALIFICACIONES_EXAMENES (
    EXAMEN_ID INTEGER NOT NULL,
    ALUMNO_ID INTEGER NOT NULL,
    CALIFICACION INTEGER NOT NULL,
    FOREIGN KEY (EXAMEN_ID) REFERENCES EXAMENES(EXAMENES_ID),
    FOREIGN KEY (ALUMNO_ID) REFERENCES ALUMNOS(ALUMNO_ID));"""
)
print("table CALIFICACIONES_EXAMENES created succesfully ")

conn.execute(
    """CREATE TABLE IF NOT EXISTS CALIFICACIONES_MATERIA (
    MATERIA_ID INTEGER NOT NULL,
    ALUMNO_ID INTEGER NOT NULL,
    CALIFICACION INTEGER NOT NULL,
    FOREIGN KEY (MATERIA_ID) REFERENCES MATERIAS(MATERIA_ID),
    FOREIGN KEY (ALUMNO_ID) REFERENCES ALUMNOS(ALUMNO_ID)
    );"""
)
print("Table CALIFICACIONES_MATERIA created succesfully")

conn.execute(
    """CREATE TABLE IF NOT EXISTS ALUMNOS_MATERIAS(
    ALUMNO_ID INTEGER,
    MATERIA_ID INTEGER,
    FOREIGN KEY (ALUMNO_ID) REFERENCES ALUMNOS(ALUMNO_ID),
    FOREIGN KEY (MATERIA_ID) REFERENCES MATERIAS(MATERIA_ID)
    );"""
)
print("Table ALUMNOS_MATERIAS created succesfully")

conn.close()
